# This playbook will gather facts about targeted host or group and save them to a log file

---
  # host passed from command line: ansible-playbook gather_server_facts.yml -e "variable_host=HOST_IN_INVENTORY"
  # by default it will lookup variable_host from the file /etc/ansible/hosts 
- hosts: "{{ variable_host | default('all') }}"
  gather_facts: false

  vars_prompt:

    # Prompt for target username
    - name: "ansible_user"
      prompt: "Username for the target machines SSH"

    # Prompt for target username's password
    - name: "ansible_ssh_pass"
      prompt: "Password for the target machines SSH"
      private: yes
    
  tasks:
  
    # Obtain a date timestamp
    - set_fact:
        date_fact: "{{lookup('pipe','date +%Y%m%d')}}"

    # Set the path used to save logging
    - set_fact:
        path_fact: "logs/"
        
    # Ensure path_fact exists
    - local_action:
        module: file
        state: directory
        path: "{{ path_fact }}"
                    
    # Gather-Facts
    - setup:
      register: out
      
    # Write facts to log file
    - local_action:
        module: copy
        content: "~~~ {{ date_fact }} {{ inventory_hostname }} Ansible Gather-Facts Diagnostic ~~~\n{{ out | to_nice_yaml }}"
        dest: "{{ path_fact }}{{ inventory_hostname }}.yml"
